-- SQL Migration for Ghars Project on Supabase
--
-- Instructions:
-- 1. Go to your Supabase project's "SQL Editor".
-- 2. Click on "New query".
-- 3. Copy and paste the entire content of this file into the editor.
-- 4. Click "Run" to execute the script and create your database tables.
-- 5. After running this, go to "Storage" and create a new public bucket named `videos` for the weekly video uploads.

-- Drop existing tables if they exist to start fresh
DROP TABLE IF EXISTS content_cards, weeks, students, classes, admins CASCADE;

-- Table for Classes
CREATE TABLE classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for Admin Users
CREATE TABLE admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    password TEXT NOT NULL UNIQUE,
    role TEXT DEFAULT 'admin',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for Students
CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    class_id BIGINT REFERENCES classes(id) ON DELETE SET NULL,
    points INT DEFAULT 0,
    role TEXT DEFAULT 'student',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for Weeks
CREATE TABLE weeks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_number INT NOT NULL,
    title TEXT NOT NULL,
    video_url TEXT,
    is_locked BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for Content Cards
CREATE TABLE content_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_id BIGINT NOT NULL REFERENCES weeks(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Initial Data
INSERT INTO admins (name, password, role) VALUES ('Default Admin', 'Xnaf*123', 'admin');

-- Sample Data (Optional)
INSERT INTO classes (name) VALUES ('Class A'), ('Class B');
INSERT INTO students (password, name, class_id, points) VALUES
('student123', 'John Doe', 1, 100),
('student456', 'Jane Smith', 2, 150);
INSERT INTO weeks (week_number, title, is_locked) VALUES (1, 'The Value of Respect', false);
INSERT INTO content_cards (week_id, title, description) VALUES (1, 'Respect in Dialogue', 'Always listen to others and value their opinions.');