-- SQL Migration for Ghars Project on Supabase
--
-- Instructions:
-- 1. Go to your Supabase project's "SQL Editor".
-- 2. Click on "New query".
-- 3. Copy and paste the entire content of this file into the editor.
-- 4. Click "Run" to execute the script and set up your database tables.
-- 5. After running this, go to "Storage" and create a new public bucket named `videos` for the weekly video uploads.
--
-- NOTE: This script will drop existing tables to ensure a clean setup.
-- Make sure to back up any important data before running it.

DROP TABLE IF EXISTS content_cards CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS weeks CASCADE;
DROP TABLE IF EXISTS classes CASCADE;
DROP TABLE IF EXISTS admins CASCADE;


-- Table for Admin Users
-- This table stores the passwords for admin access.
CREATE TABLE admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for Classes
-- Stores the different classes students can belong to.
CREATE TABLE classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for Students
-- Stores student information, including their unique password for login.
CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    class_id BIGINT REFERENCES classes(id) ON DELETE SET NULL, -- Foreign key to the classes table
    points INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for Weeks
-- Holds the content for each week.
CREATE TABLE weeks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_number INT NOT NULL,
    title TEXT NOT NULL,
    video_url TEXT, -- This will store the public URL of the video from Supabase Storage
    is_locked BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for Content Cards
-- These are the descriptive cards associated with each week.
CREATE TABLE content_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_id BIGINT NOT NULL REFERENCES weeks(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Initial Data (Optional)
-- You can add an initial admin password here to get started.
-- Replace 'your_secret_admin_password' with the actual password you want to use.
INSERT INTO admins (password) VALUES ('Xnaf*123');

-- You can also add some initial classes.
INSERT INTO classes (name) VALUES ('الصف الأول'), ('الصف الثاني'), ('الصف الثالث');